---
- name: Global Admin Push
  hosts: webserver
  become: true

  tasks:
    - name: add user
      ansible.builtin.user:
        name: gbadmin
        groups: wheel
      #generate_ssh_key: yes
      #ssh_key_bits: 2048
      #ssh_key_file: .ssh/id_rsa

    - name: Set authorized key taken from file
      ansible.posix.authorized_key:
        user: gbadmin
        state: present
        key: "{{ lookup('file', '/home/gbadmin/.ssh/gbadmin.pub') }}"
